# Generated by Django 5.2.7 on 2025-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
    ]
