# Generated by Django 5.2.7 on 2025-11-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20),
        ),
        migrations.AddField(
            model_name='dog',
            name='coat_grooming',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20),
        ),
        migrations.AddField(
            model_name='dog',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='training_difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Challenging', 'Challenging')], max_length=20),
        ),
        migrations.AddField(
            model_name='dog',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
