# Generated by Django 5.2.7 on 2025-11-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dog_activity_level_dog_coat_grooming_dog_height_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='microchip_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
