# Generated by Django 5.2.7 on 2025-11-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='housing_document',
            field=models.FileField(blank=True, help_text='Upload your housing / tenancy document as a PDF.', null=True, upload_to='housing_docs/'),
        ),
    ]
