# Generated by Django 5.2.7 on 2026-01-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_remove_clientprofile_housing_document_alter_dog_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='housing_document',
            field=models.FileField(blank=True, help_text='Upload your housing / tenancy document as a PDF.', null=True, upload_to='housing_docs/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='microchip_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='AdoptionRequest',
        ),
    ]
