# Generated by Django 5.2.7 on 2026-01-22 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0009_dog_status_notification_adoptionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dogs/multi/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dogs.dog')),
            ],
        ),
    ]
